
odsay:
  uri: https://api.odsay.com/v1/api/searchPubTransPathT
  key: Fa1c1EUOHGdzHQ16b51eiLa9G%2Bl12%2FJHetKVLcphpjI
  arsId: https://api.odsay.com/v1/api/searchStation
  realTimeStation: https://api.odsay.com/v1/api/realtimeStation

google:
  uri: https://maps.googleapis.com/maps/api/geocode/json
  key: AIzaSyDI5ze-G_qR4uril-uYFwvFSH56UVSUqxk

seoul:
  uri: http://swopenAPI.seoul.go.kr/api/subway/634d57594162736837397a416d5656/json/realtimeStationArrival/0/10/

spring:
  datasource:
    url: jdbc:mysql://commute-map.cpzzz73ewjdq.ap-northeast-2.rds.amazonaws.com:3306/commuteMapDB
    username: bsh6463
    password: bae930224!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

