odsay:
  uri: https://api.odsay.com/v1/api/searchPubTransPathT
  key: Fa1c1EUOHGdzHQ16b51eiLa9G%2Bl12%2FJHetKVLcphpjI

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/commuteMap
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug